i = int(input())
print(f' @@@   @@@  '*i)
print(f'@   @ @   @ '*i)
print(f'@    @    @ '*i)
print(f'@         @ '*i)
print(f' @       @  '*i)
print(f'  @     @   '*i)
print(f'   @   @    '*i)
print(f'    @ @     '*i)
print(f'     @      '*i)